WIP

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -105,13 +105,13 @@ default_test_config: &default_test_config
     - sudo apt-get install -y jq unzip
   before_script:
     # --no-sign-request allows access without credentials, as long as we specify the region.
-    #    - NUM_VERSIONS=$(aws --no-sign-request --region us-east-1 s3api list-object-versions
-    #          --bucket ${BOOTSTRAPPED_PEX_BUCKET} --prefix ${BOOTSTRAPPED_PEX_KEY} --max-items 2
-    #      | jq '.Versions | length')
-    #    - if [ "${NUM_VERSIONS}" != "1" ]; then
-    #        echo "Error: Found ${NUM_VERSIONS} versions for ${BOOTSTRAPPED_PEX_URL}"
-    #        exit 1
-    #      fi
+    - NUM_VERSIONS=$(aws --no-sign-request --region us-east-1 s3api list-object-versions
+          --bucket ${BOOTSTRAPPED_PEX_BUCKET} --prefix ${BOOTSTRAPPED_PEX_KEY} --max-items 2
+      | jq '.Versions | length')
+    - if [ "${NUM_VERSIONS}" != "1" ]; then
+        echo "Error: Found ${NUM_VERSIONS} versions for ${BOOTSTRAPPED_PEX_URL}"
+        exit 1
+      fi
     - aws --no-sign-request --region us-east-1 s3 cp ${BOOTSTRAPPED_PEX_URL} ./pants.pex
     - chmod 755 ./pants.pex
     # Pants code executing under test expects the native_engine.so to be present as a resource
