WIP

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -92,9 +92,19 @@ default_test_config: &default_test_config
     # files in the working copy.
     - sudo sysctl fs.inotify.max_user_watches=524288
     - pip install awscli
+    # Multipart operations aren't supported for anonymous users, so we set the
+    # threshold high to avoid them being used automatically by the aws cli.
+    - aws configure set default.s3.multipart_threshold 1024MB
     - sudo apt-get install -y jq
   before_script:
     # --no-sign-request allows access without credentials, as long as we specify the region.
+    - NUM_VERSIONS=$(aws --no-sign-request --region us-east-1 s3api list-object-versions
+          --bucket ${BOOTSTRAPPED_PEX_BUCKET} --key ${BOOTSTRAPPED_PEX_KEY}
+      | jq '.Versions | length')
+    - if [ "${NUM_VERSIONS}" != "1" ]; then
+        echo "Error: Found ${NUM_VERSIONS} versions for ${BOOTSTRAPPED_PEX_URL}"
+        exit 1
+      fi
     - aws --no-sign-request --region us-east-1 s3 cp ${BOOTSTRAPPED_PEX_URL} ./pants.pex
 
 osx_test_config: &osx_test_config
@@ -124,8 +134,7 @@ matrix:
       stage: *bootstrap
       before_script:
       script:
-        - ./build-support/bin/travis-ci.sh  # With no args, just bootstraps.
-      after_success:
+        - ./build-support/bin/travis-ci.sh  # With no args this script just bootstraps.
         - aws --no-sign-request --region us-east-1 s3 cp ./pants.pex ${BOOTSTRAPPED_PEX_URL}
 
     # Build macOS engine
