Include the Pants native client in released wheels (#18957)
The Pants native client which was introduced in #11922 has so far only
been usable in the Pants repo when the `USE_NATIVE_PANTS` environment
variable was set.

To make the native client available to end users, this change begins
distributing the native-client binary in Pants wheels. A corresponding
change in the `scie-pants` repo
(https://github.com/pantsbuild/scie-pants/pull/172) uses the native
client to run `pants`.

To reduce the surface area of `scie-pants` (rather than having it be
responsible for handling the special `75` exit code similar to the
`pants` script integration), this PR also moves to having the
native-client execute its own fallback (via `execv`) to the Pants
entrypoint. In future, the `pantsbuild/pants` `pants` script could also
use that facility (e.g. by specifying a separate `pants_server` bash
script as the entrypoint to use as the `_PANTS_SERVER_EXE`).

----

As originally demonstrated on #11831, the native client is still much
faster than the legacy client. Using
https://github.com/pantsbuild/scie-pants/pull/172, the timings look
like:
```
Benchmark #1: PANTS_NO_NATIVE_CLIENT=true PANTS_SHA=836cceb74e6af042e7c82677f3ceb4927efce20e scie-pants-macos-x86_64 help
  Time (mean ± σ):      1.161 s ±  0.067 s    [User: 830.6 ms, System: 79.2 ms]
  Range (min … max):    1.054 s …  1.309 s    10 runs

Benchmark #2: PANTS_SHA=836cceb74e6af042e7c82677f3ceb4927efce20e scie-pants-macos-x86_64 help
  Time (mean ± σ):     271.0 ms ±  30.6 ms    [User: 8.9 ms, System: 6.9 ms]
  Range (min … max):   241.5 ms … 360.6 ms    12 runs

Summary
  'PANTS_SHA=836cceb74e6af042e7c82677f3ceb4927efce20e scie-pants-macos-x86_64 help' ran
    4.29 ± 0.54 times faster than 'PANTS_NO_NATIVE_CLIENT=true PANTS_SHA=836cceb74e6af042e7c82677f3ceb4927efce20e scie-pants-macos-x86_64 help'
```

Fixes #11831.

diff --git a/pants b/pants
--- a/pants
+++ b/pants
@@ -41,7 +41,6 @@ source "${HERE}/build-support/pants_venv"
 source "${HERE}/build-support/bin/rust/bootstrap_code.sh"
 
 function exec_pants_bare() {
-  PANTS_NATIVE_EXE="${HERE}/.pants"
   PANTS_PY_EXE="${HERE}/src/python/pants/bin/pants_loader.py"
   PANTS_SRCPATH="${HERE}/src/python"
 
@@ -49,9 +48,18 @@ function exec_pants_bare() {
   activate_pants_venv 1>&2
   bootstrap_native_code 1>&2
 
-  if [ -n "${USE_NATIVE_PANTS}" ]; then
+  if [ -n "${PANTS_DEBUG}" ]; then
+    if [[ "$*" != *"--no-pantsd"* ]]; then
+      echo "Error! Must pass '--no-pantsd' when using PANTS_DEBUG"
+      exit 1
+    fi
+    DEBUG_ARGS="-m debugpy --listen 127.0.0.1:5678 --wait-for-client"
+    echo "Will launch debugpy server at '127.0.0.1:5678' waiting for client connection."
+  fi
+
+  if [ -z "${PANTS_NO_NATIVE_CLIENT}" ]; then
     set +e
-    "${PANTS_NATIVE_EXE}" "$@"
+    "${NATIVE_CLIENT_BINARY}" "$@"
     result=$?
     # N.B.: The native pants client currently relies on pantsd being up. If it's not, it will fail
     # with exit code 75 (EX_TEMPFAIL in /usr/include/sysexits.h) and we should fall through to the
@@ -61,15 +69,6 @@ function exec_pants_bare() {
       exit ${result}
     fi
     set -e
-  fi
-
-  if [ -n "${PANTS_DEBUG}" ]; then
-    if [[ "$*" != *"--no-pantsd"* ]]; then
-      echo "Error! Must pass '--no-pantsd' when using PANTS_DEBUG"
-      exit 1
-    fi
-    DEBUG_ARGS="-m debugpy --listen 127.0.0.1:5678 --wait-for-client"
-    echo "Will launch debugpy server at '127.0.0.1:5678' waiting for client connection."
   fi
 
   # shellcheck disable=SC2086
