This month brings the release candidate for a new pants build system and many additions and improvements to the python application framework.
pants:
  + Add support for excluding java or scala from ide configurations
  + Fix idea checkstyle integration to include all suppression files
  + Support forward references in BUILD files
  + Fixup eclipse support so that the generated project recognizes any annotation_processors
  + Add a PANTS_DEV option to run pants straight from the repo sources to ease the pants dev cycle
  + Cache git build info to avoid running expensive git commands on every build
  + Add marker files for checkstyle runs to eliminate unnecessary checkstyle invocations
  + Add a doc target that supports conversion of markdown to html and nesting other doc dependencies

python:
  + Added support for subcommands and ini file based flag defaulting for subcommands
  + Added support for installable modules and provide logging and an http server in this form
  + Added jvm Amount analog along with a metrics module and /vars HTTP handler
  + Add glog style log file rolling
  + Added an Atlassian Confluence wiki posting component
  + Upgrade pytest to 2.6
  + Resource pool implementation
  + Added caching support to pants python builds
  + Basic ServerSet client
  + Improvements to java classfile parser
  + Add a file tailer
  + Support PEX_INHERIT_PATH to allow a pex to inherit the PYTHONPATH

jvm:
  Upgrade to guava 11.0.1, zookeeper 3.3.4 and finaglized thrift compiler

  app:
    + Implement a local service registry for startup actions, use this to boot the HTTP server
    + Several fixes and improvements to ShutdownRegistry ands its integration with AppLauncher
    + ExecutorServiceShutdown to encapsulate an orderly shutdown of an ExecutorService

  args:
    + @Positional Arg<List<T>> is now supported for gathering positional args
    + Added a twitter util Duration parser that uses Amount<Long, Time> syntax
    + Added a RangeParser to parse guava Ranges
    + Added support for registering custom Parsers and Verifiers globally via annotations+apt
    + Add CanExecute Verifier for files

  base:
    + Introduce a CachingSupplier

  objectsize:
    + Now has a public artifact: com.twitter.common#objectsize
    + Refactor to be parameterizable to arbitrary JVM memory layouts by the user

  reflect:
    + Added simple TypeToken based on guice's TypeLiteral but without the dependency burden

  stats:
    + Added ReservoirSampler - an implementation of http://en.wikipedia.org/wiki/Reservoir_sampling
    + Added Elapsed counting stat that reports the time since it was reset.
    + Added a /vars handler that exports data in JSON format and sort /vars text handler output
    + Added per pool gc cycle count and gc time, fd stats and more thread stats to JvmStats
    + Percentile improvements including support for multiple sampling windows

  testing:
    + TearDownRegistry to adapt a TearDownTestCase to an ShutdownRegistry used for shutdowns

  text:
    + Add a TokenStream(De)Serializer for serialization of TokenStreams and arbitrary attributes
    + Better definitions of punctuation
    + Rename PossetiveTokenCombiner to PossessiveContractionTokenCombiner and modify it to combine tokens in contraction form.
    + Implement JapaneseGomokuTokenizer, and remove JapaneseMeCabTokenizer

  util:
    + Utilities for working with temporary files and directories

  zookeeper:
    + The com.twitter.common#zookeeper jar has been broken up into one jar per major component

(sapling split of 9fc05c8cc927ade33cb14ee21d433669af218c91)

diff --git a/pants b/pants
--- a/pants
+++ b/pants
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # ==================================================================================================
 # Copyright 2011 Twitter, Inc.
 # --------------------------------------------------------------------------------------------------
@@ -16,12 +16,48 @@
 # ==================================================================================================
 
 MY_DIR=$(dirname $0)
-export BUILD_ROOT=${MY_DIR}
-export PYTHONPATH=${MY_DIR}/src/python
+VIRTUAL_PYTHON=$MY_DIR/.python
+
+PANTS_EXE=$MY_DIR/src/python/twitter/pants/bin/pants_exe.py
+MAKO_EGG=$MY_DIR/3rdparty/python/Mako-0.4.0-py2.6.egg
+MARKDOWN_EGG=$MY_DIR/3rdparty/python/Markdown-2.0.3-py2.6.egg
+ELEMENTTREE_EGG=$MY_DIR/3rdparty/python/elementtree-1.2.7_20070827_preview-py2.6.egg
+
+function run_pants_bare() {
+  source $VIRTUAL_PYTHON/bin/activate
+  PYTHONPATH=$MAKO_EGG:$MARKDOWN_EGG:$ELEMENTTREE_EGG:$MY_DIR/src/python python $PANTS_EXE "$@"
+  deactivate
+}
+
+if [ ! -e $VIRTUAL_PYTHON/bin/python ]; then
+  $MY_DIR/build-support/bootstrap/bootstrap.sh
+  rc=$?
+  if [[ $rc != 0 ]]; then
+    echo "Unable to bootstrap a sane Python virtual environment for pants!"
+    rm -rf $VIRTUAL_PYTHON
+    exit $rc
+  fi
+fi
+
+if [ -z "${PANTS_DEV}" -a ! -e $MY_DIR/pants.pex ]; then
+  run_pants_bare src/python/twitter/pants:pants
+  if [ ! -e $MY_DIR/dist/pants.pex ]; then
+    echo "Unable to build pants!  Cannot continue!"
+    exit
+  else
+    mv $MY_DIR/dist/pants.pex $MY_DIR/pants.pex
+  fi
+fi
 
 if [ -z "$ANT_OPTS" ]; then
   export ANT_OPTS="-Xmx1g -XX:MaxPermSize=512m"
 fi
 
-PYTHON=${PYTHON:=/usr/bin/env python2.6}
-${PYTHON} ${MY_DIR}/src/python/twitter/pants/bin/pants_exe.py "$@"
+if [ ! -z "${PANTS_DEV}" ]; then
+  # TODO(John Sirois): ideally this would just use pants.pex to run the pants target in py mode:
+  # ./pants.pex py src/python/twitter/pants "$@"
+  echo "*** running pants in dev mode from $PANTS_EXE ***"
+  run_pants_bare "$@"
+else
+  ${MY_DIR}/pants.pex "$@"
+fi
