cache the venv and rust build dirs in a shared cache dir

diff --git a/build-support/pants_venv b/build-support/pants_venv
--- a/build-support/pants_venv
+++ b/build-support/pants_venv
@@ -64,9 +64,21 @@ function activate_pants_venv() {
   done
   fingerprint=$(echo "${fingerprint}" | fingerprint_data)
 
+  # The $BOOTSTRAPPED_DIR is in a cache shared across all pants checkouts.
   BOOTSTRAPPED_FILE="$(venv_dir)/BOOTSTRAPPED.${fingerprint}"
+  BOOTSTRAPPED_DIR="${CACHE_ROOT}/virtualenvs/$(uname)/${fingerprint}"
 
-  if ! [ -f "${BOOTSTRAPPED_FILE}" ]; then
+  if [ -d "${BOOTSTRAPPED_DIR}" ]; then
+    # If this venv was found within the shared cache, but the venv dir in the current pants checkout
+    # is not up to date, delete the venv dir and copy over the venv from the shared cache.
+    if ! [[ -f "${BOOTSTRAPPED_FILE}" ]]; then
+      rm -rf "$(venv_dir)"
+      mkdir -pv "$(dirname "$(venv_dir)")"
+      cp -r "${BOOTSTRAPPED_DIR}" "$(venv_dir)"
+      touch "${BOOTSTRAPPED_FILE}"
+    fi
+    activate_venv || die "Failed to activate venv."
+  else
     log "Bootstrapping pants_deps with requirements:"
     # Use -f ${REPO_ROOT}/third_party if patching in local dependencies like so
     # pip_extra="-f ${REPO_ROOT}/third_party"
@@ -86,9 +98,12 @@ function activate_pants_venv() {
       pip install ${pip_extra} -r "${req}" || \
         die "Failed to install requirements from ${req}."
     done
+
+    # Write the current venv to the shared cache.
     touch "${BOOTSTRAPPED_FILE}"
-  else
-    activate_venv || die "Failed to activate venv."
+    if [[ ! -d "${BOOTSTRAPPED_DIR}" ]]; then
+      mkdir -pv "$(dirname "${BOOTSTRAPPED_DIR}")"
+      cp -r "$(venv_dir)" "${BOOTSTRAPPED_DIR}"
+    fi
   fi
 }
-
