add some guards in the pants shell script bootstrapping for binaries not getting found

diff --git a/build-support/pants_venv b/build-support/pants_venv
--- a/build-support/pants_venv
+++ b/build-support/pants_venv
@@ -34,19 +34,22 @@ function create_venv() {
 }
 
 function ensure_gcc() {
-  GCC_VERSION=$(gcc -v 2>&1)
-  if (( $? != 0 )); then
+  if ! gcc -v &>/dev/null; then
+    # The output was swallowed last time to avoid output in the success case, so we repeat the
+    # command's output again to stderr if it fails.
+    gcc -v >&2
     die "$(cat << MESSAGE
 ERROR: unable to execute 'gcc'. Please verify that your compiler is installed, in your
        \$PATH and functional.
 
 Hint: on Mac OS X, you may need to accept the XCode EULA: 'sudo xcodebuild -license accept'.
+Alternatively, if gcc was not found at all, you may need to run 'sudo xcode-select --install'.
 MESSAGE
 )"
   fi
   # Prevent bootstrapping failure due to unrecognized flag:
   # https://github.com/pantsbuild/pants/issues/78
-  if [[ "$GCC_VERSION" == *503.0.38* ]]; then
+  if [[ "$(gcc -v 2>&1)" == *503.0.38* ]]; then
     # Required for clang version 503.0.38
     export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future
   fi
@@ -86,4 +89,3 @@ function activate_pants_venv() {
     activate_venv || die "Failed to activate venv."
   fi
 }
-
