- Create VIRTUALENV_PACKAGE_LOCATION env var so we can customize virtualenv package download - Refactor to have a common.sh containing the set_archflags and logging functionalities. - Make the virtual env script a bit more robust against curl/tar/activate errors
Testing Done:
manually tested:
1) not specifying VIRTUALENV_PACKAGE_LOCATION,
2) specifying a valid custom VIRTUALENV_PACKAGE_LOCATION location, and
3) specifying an invalid VIRTUALENV_PACKAGE_LOCATION location.

Travis: https://travis-ci.org/jinfeng/jinfeng-pants-fork/builds/40690744

Reviewed at https://rbcommons.com/s/twitter/r/1316/

diff --git a/build-support/pants_venv b/build-support/pants_venv
--- a/build-support/pants_venv
+++ b/build-support/pants_venv
@@ -3,8 +3,7 @@
 # Licensed under the Apache License, Version 2.0 (see LICENSE).
 
 REPO_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}") && cd "$(git rev-parse --show-toplevel)" && pwd)
-
-source ${REPO_ROOT}/build-support/set_archflags.sh
+source ${REPO_ROOT}/build-support/common.sh
 
 REQUIREMENTS=(
   ${REPO_ROOT}/3rdparty/python/requirements.txt
@@ -16,15 +15,6 @@ REQUIREMENTS=(
 DEV_REQUIREMENTS=(
   ${REPO_ROOT}/3rdparty/python/dev_only_requirements.txt
 )
-
-function log() {
-  echo -e "$@" 1>&2
-}
-
-function die() {
-  (($# > 0)) && log "$@"
-  exit 1
-}
 
 function venv_dir() {
   if [ ! -z "${PANTS_DEV}" ]; then
@@ -78,14 +68,14 @@ function activate_pants_venv() {
       log "  ${req}"
     done
 
-    create_venv
-    activate_venv
+    create_venv || die "Failed to create venv."
+    activate_venv || die "Failed to activate venv."
     for req in ${REQUIREMENTS[@]}; do
       pip install ${pip_extra} -r "${req}" || die "Failed to install requirements from ${req}."
     done
     touch "${BOOTSTRAPPED_FILE}"
   else
-    activate_venv
+    activate_venv || die "Failed to activate venv."
   fi
 }
 
