address RB comments: adding mv set_archflags.sh to common.sh and add logging funcs there

diff --git a/build-support/virtualenv b/build-support/virtualenv
--- a/build-support/virtualenv
+++ b/build-support/virtualenv
@@ -2,39 +2,35 @@
 # Wrapper for self-bootstrapping virtualenv
 set -e
 VIRTUALENV_VERSION=1.11.4
-
 VIRTUALENV_PACKAGE_LOCATION=${VIRTUALENV_PACKAGE_LOCATION:-https://pypi.python.org/packages/source/v/virtualenv}
 
-function log() {
-  echo -e "$@" 1>&2
-}
+REPO_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}") && cd "$(git rev-parse --show-toplevel)" && pwd)
+source ${REPO_ROOT}/build-support/common.sh
 
-function die() {
-  (($# > 0)) && log "$@"
-  exit 1
-}
 
 if [[ -z "$PY" ]]; then
   if which python2.7 >/dev/null; then
     PY=`which python2.7`
   else
-    die 'No python2.7 interpreter found on the path.  Python will not work!' 1>&2
+    die 'No python2.7 interpreter found on the path.  Python will not work!'
   fi
 fi
 
 log "Using $PY"
 
 HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
-if ! [ -f "$HERE/virtualenv-$VIRTUALENV_VERSION/BOOTSTRAPPED" ]; then
+BOOTSTRAP_FILE=$HERE/virtualenv-${VIRTUALENV_VERSION}/BOOTSTRAPPED
+if ! [ -f "${BOOTSTRAP_FILE}" ]; then
   pushd "$HERE"
-  log "Downloading ${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-$VIRTUALENV_VERSION.tar.gz..."
-  curl -O ${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-$VIRTUALENV_VERSION.tar.gz || \
-    die "Failed to download ${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-$VIRTUALENV_VERSION.tar.gz."
+  VIRTUALENV_PACKAGE_FULL_URL=${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-${VIRTUALENV_VERSION}.tar.gz
+  log "Downloading ${VIRTUALENV_PACKAGE_FULL_URL}..."
+  curl -O ${VIRTUALENV_PACKAGE_FULL_URL} || \
+    die "Failed to download ${VIRTUALENV_PACKAGE_FULL_URL}."
   tar zxvf virtualenv-$VIRTUALENV_VERSION.tar.gz || \
-    die "Failed to extract ${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-$VIRTUALENV_VERSION.tar.gz."
+    die "Failed to extract ${VIRTUALENV_PACKAGE_FULL_URL}."
   # TODO(ksweeney): Checksum
-  touch virtualenv-$VIRTUALENV_VERSION/BOOTSTRAPPED  # 2PC
+  touch ${BOOTSTRAP_FILE}  # 2PC
   popd
 fi
 
-exec "$PY" "$HERE/virtualenv-$VIRTUALENV_VERSION/virtualenv.py" "$@"
+exec "$PY" "$HERE/virtualenv-${VIRTUALENV_VERSION}/virtualenv.py" "$@"
