Setup MyPy config and enforce types for build-support scripts (#7704)
### Problem
We would like to use type hints throughout our code base, per https://github.com/pantsbuild/pants/issues/6742.

However, we must configure it with sensible defaults to make it easier to use and to provide a consistent interface for developers.

We should also enforce as much type safety as we can via our `pre-commit` check.

### Solution
* Add new `mypy.ini` file with fairly loose defaults that are good for first time codebases. Eventually, we will want to do things like require all functions to be typed, but for now we loosen our expectations.
* Link to the config file in `pants.ini`, along with using the most modern MyPy release which gives us  the `strict_equality` check.
* Run `mypy.py` over the build-support scripts, which are fully typed.
   * Acts as a proof of concept for how this will be integrated into CI.

### Result
`./pants mypy` is now a bit more useful on our codebase, even though it will still fail because of pre-existing issues.

Further, the build-support folder will not have any typing regressions now.

diff --git a/build-support/githooks/pre-commit b/build-support/githooks/pre-commit
--- a/build-support/githooks/pre-commit
+++ b/build-support/githooks/pre-commit
@@ -58,6 +58,12 @@ if git rev-parse --verify "${MERGE_BASE}" &>/dev/null; then
   # quite often with a pexrc available.
   echo "* Checking lint" && ./pants --exclude-target-regexp='testprojects/.*' --changed-parent="${MERGE_BASE}" lint || exit 1
 
+  echo "* Checking types (for build-support)"
+  # NB: This task requires Python 3, so we must temporarily override any intepreter constraints
+  # set by ci.sh, specifically it setting constraints to Python 2, because those constraints may
+  # cause a select-interpreter failure.
+  PANTS_PYTHON_SETUP_INTERPRETER_CONSTRAINTS="['CPython>=3.6']" ./pants mypy 'build-support::' || exit 1
+
   if git diff "${MERGE_BASE}" --name-only | grep '\.rs$' > /dev/null; then
     echo "* Checking formatting of rust files" && ./build-support/bin/check_rust_formatting.sh || exit 1
     # Clippy happens on a different Travis CI shard because of separate caching concerns.
